--- #YAML:1.0
name:                     Data-Phrasebook-Loader-Ini
version:                  0.13
abstract:                 Loader class for phrasebook implementations using INI files
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  perl:                   5.006
  Carp:                   0
  Config::IniFiles:       0
  Data::Phrasebook:       0.24
recommends:
  Test::CPAN::Meta:       0
  Test::CPAN::Meta::JSON: 0
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
build_requires:
  IO::File:               0
  Test::More:             0.70

provides:
  Data::Phrasebook::Loader::Ini:
    file:     lib/Data/Phrasebook/Loader/Ini.pm
    version:  0.13
no_index:
  directory:
    - t
    - examples

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Data-Phrasebook-Loader-Ini

meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Hand 1.0
