# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-Phrasebook-Loader-Ini
version:      0.08
version_from: lib/Data/Phrasebook/Loader/Ini.pm
installdirs:  site
requires:
    Config::IniFiles:              0
    Data::Phrasebook:              0.23
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
